In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
x = torch.empty(5, 3)
x

tensor([[ 1.3476e+37,  3.5219e-41,  2.2561e-43],
        [ 0.0000e+00,  9.5272e-38,  4.1892e-41],
        [ 9.5272e-38,  4.1892e-41, -6.3008e+19],
        [ 3.5219e-41, -6.3017e+19,  3.5219e-41],
        [-6.3023e+19,  3.5219e-41, -6.3027e+19]])

In [4]:
torch.rand(5, 3)

tensor([[0.9683, 0.4082, 0.7795],
        [0.1931, 0.1348, 0.0181],
        [0.0595, 0.2159, 0.2452],
        [0.3789, 0.0834, 0.0296],
        [0.9357, 0.2758, 0.1092]])

In [5]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.Tensor(5, 3)

tensor([[2.1715e-18, 1.3089e+22, 6.6009e-07],
        [1.3457e+22, 4.2958e-05, 4.1337e-05],
        [1.0299e-11, 3.3462e+21, 5.3540e+22],
        [3.2916e-09, 2.1707e-18, 4.5447e+30],
        [7.0062e+22, 2.1715e-18, 4.5447e+30]])

In [7]:
torch.Tensor([5.5, 3.3])

tensor([5.5000, 3.3000])

In [8]:
x = torch.ones(5, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
y = torch.randn_like(x, dtype=torch.double)
y

tensor([[-1.2142,  0.1266,  1.7019],
        [-1.1042,  0.2563,  0.7465],
        [ 0.4298,  0.3328, -0.5397],
        [-2.2847,  1.6239, -1.0423],
        [-1.0019, -2.4007, -0.4449]], dtype=torch.float64)

In [10]:
print(y.shape)
print(y.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [11]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[0.9519, 0.6418, 0.6871],
        [1.0635, 1.2846, 1.0571],
        [0.2616, 1.2110, 0.6385],
        [1.3651, 1.2012, 1.1792],
        [1.5541, 1.7459, 0.8515]])
tensor([[0.9519, 0.6418, 0.6871],
        [1.0635, 1.2846, 1.0571],
        [0.2616, 1.2110, 0.6385],
        [1.3651, 1.2012, 1.1792],
        [1.5541, 1.7459, 0.8515]])


In [12]:
print(y)
print(y.add_(x))
print(y)

tensor([[0.7011, 0.6154, 0.1791],
        [0.0678, 0.7475, 0.6463],
        [0.2306, 0.7913, 0.4562],
        [0.5973, 0.8600, 0.7304],
        [0.6659, 0.8472, 0.7911]])
tensor([[0.9519, 0.6418, 0.6871],
        [1.0635, 1.2846, 1.0571],
        [0.2616, 1.2110, 0.6385],
        [1.3651, 1.2012, 1.1792],
        [1.5541, 1.7459, 0.8515]])
tensor([[0.9519, 0.6418, 0.6871],
        [1.0635, 1.2846, 1.0571],
        [0.2616, 1.2110, 0.6385],
        [1.3651, 1.2012, 1.1792],
        [1.5541, 1.7459, 0.8515]])


In [13]:
a = torch.rand(4, 4)
b = torch.rand(4, 4)
c = torch.empty(4, 4)
torch.add(a, b, out=c)
print(c)

tensor([[1.1157, 1.0092, 0.1299, 1.3040],
        [0.9633, 0.6102, 0.9435, 1.9456],
        [0.9522, 1.3837, 1.4477, 0.5600],
        [1.1552, 0.9478, 0.6326, 0.8735]])


In [14]:
a

tensor([[0.9295, 0.7416, 0.0086, 0.7627],
        [0.8877, 0.1733, 0.5540, 0.9848],
        [0.6019, 0.9162, 0.7833, 0.4489],
        [0.9895, 0.6923, 0.3471, 0.6801]])

In [15]:
a[:, 1]

tensor([0.7416, 0.1733, 0.9162, 0.6923])

In [16]:
x = torch.rand(4, 4)
x.shape

torch.Size([4, 4])

In [17]:
x.view(16)

tensor([0.6206, 0.0246, 0.8591, 0.7210, 0.2680, 0.1565, 0.9107, 0.7034, 0.8695,
        0.6714, 0.9303, 0.0607, 0.9489, 0.6437, 0.4980, 0.5605])

In [18]:
y = x.view(-1, 8)
y

tensor([[0.6206, 0.0246, 0.8591, 0.7210, 0.2680, 0.1565, 0.9107, 0.7034],
        [0.8695, 0.6714, 0.9303, 0.0607, 0.9489, 0.6437, 0.4980, 0.5605]])

In [19]:
x = torch.rand(1)
x

tensor([0.7464])

In [20]:
x.item()

0.746386706829071

In [21]:
x = torch.rand(3, 3)
x

tensor([[0.6948, 0.6136, 0.0867],
        [0.8672, 0.0050, 0.5455],
        [0.2834, 0.2585, 0.2266]])

In [22]:
y = x[0, 0]
y.item()

0.6948241591453552

In [23]:
y = x.numpy()
y

array([[0.69482416, 0.61360025, 0.0867334 ],
       [0.8672247 , 0.00497037, 0.54553616],
       [0.2833588 , 0.25849092, 0.22664112]], dtype=float32)

In [24]:
y[0, 0]

0.69482416

In [25]:
import numpy as np

a = np.ones(3)
a

array([1., 1., 1.])

In [26]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [27]:
device = torch.cuda.is_available()
device

True

In [28]:
x

tensor([[0.6948, 0.6136, 0.0867],
        [0.8672, 0.0050, 0.5455],
        [0.2834, 0.2585, 0.2266]])

In [29]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)

z = z.cpu()
print(z)

tensor([[1.6948, 1.6136, 1.0867],
        [1.8672, 1.0050, 1.5455],
        [1.2834, 1.2585, 1.2266]], device='cuda:0')


tensor([[1.6948, 1.6136, 1.0867],
        [1.8672, 1.0050, 1.5455],
        [1.2834, 1.2585, 1.2266]])
